[package]
name = "waloyo_app"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.42", features = ["serde"] }
dirs = "6.0.0"
gpui = { path = "../zed/crates/gpui" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
